#Configuracion de los contenedores de Docker para la aplicacion
services:
  frontend:
    image: client:1.0-ie1
    build:
      context: ./client
    container_name: intento-examen-1-frontend
    ports:
      - "3080:80"
    networks:
      - ie-net

  backend:
    image: server:1.0-ie1
    build:
      context: ./server
    container_name: intento-examen-1-backend
    environment:
      SERVER_PORT: 8080
    ports:
      - "8082:8080"
    networks:
      - ie-net
    depends_on:
      - frontend

#CONFIGURACION DE LA RED Y VOLUMENES
networks:
  ie-net:
    external: true

volumes:
  ie-volume:
    external: true